-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- /																	DOORS																      --/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
local SMT = {}
SMT.SmallBridge = {}
SMT.SmallBridge["Hulls (SW)"] = {
    "models/smallbridge/hulls_sw/sbhullcurvel.mdl",
    "models/smallbridge/hulls_sw/sbhullcurvem.mdl",
    "models/smallbridge/hulls_sw/sbhullcurves.mdl",
    "models/smallbridge/hulls_sw/sbhulle05.mdl",
    "models/smallbridge/hulls_sw/sbhulle1.mdl",
    "models/smallbridge/hulls_sw/sbhulle2.mdl",
    "models/smallbridge/hulls_sw/sbhulle3.mdl",
    "models/smallbridge/hulls_sw/sbhulle4.mdl",
    "models/smallbridge/hulls_sw/sbhulledh.mdl",
    "models/smallbridge/hulls_sw/sbhulledh05.mdl",
    "models/smallbridge/hulls_sw/sbhulledh2.mdl",
    "models/smallbridge/hulls_sw/sbhulledh3.mdl",
    "models/smallbridge/hulls_sw/sbhulledh4.mdl",
    "models/smallbridge/hulls_sw/sbhulleflip.mdl",
    "models/smallbridge/hulls_sw/sbhullend.mdl",
    "models/smallbridge/hulls_sw/sbhullenddh.mdl",
    "models/smallbridge/hulls_sw/sbhullr.mdl",
    "models/smallbridge/hulls_sw/sbhullrdh.mdl",
    "models/smallbridge/hulls_sw/sbhullrtri.mdl",
    "models/smallbridge/hulls_sw/sbhullslanthalfl.mdl",
    "models/smallbridge/hulls_sw/sbhullslanthalfr.mdl",
    "models/smallbridge/hulls_sw/sbhullslantl.mdl",
    "models/smallbridge/hulls_sw/sbhullslantr.mdl",
    "models/smallbridge/hulls_sw/sbhullt.mdl",
    "models/smallbridge/hulls_sw/sbhulltdh.mdl",
    "models/smallbridge/hulls_sw/sbhulltdl.mdl",
    "models/smallbridge/hulls_sw/sbhulltdldw.mdl",
    "models/smallbridge/hulls_sw/sbhulltri1.mdl",
    "models/smallbridge/hulls_sw/sbhulltri2.mdl",
    "models/smallbridge/hulls_sw/sbhulltri3.mdl",
    "models/smallbridge/hulls_sw/sbhullx.mdl",
    "models/smallbridge/hulls_sw/sbhullxdh.mdl",
    "models/smallbridge/hulls_sw/sbhullxdl.mdl",
    "models/smallbridge/hulls_sw/sbhullxdldw.mdl"
}

SMT.SmallBridge["Hulls (DW)"] = {
    "models/smallbridge/hulls_dw/sbhulldwe05.mdl",
    "models/smallbridge/hulls_dw/sbhulldwe1.mdl",
    "models/smallbridge/hulls_dw/sbhulldwe2.mdl",
    "models/smallbridge/hulls_dw/sbhulldwe3.mdl",
    "models/smallbridge/hulls_dw/sbhulldwe4.mdl",
    "models/smallbridge/hulls_dw/sbhulldwedh.mdl",
    "models/smallbridge/hulls_dw/sbhulldwedh05.mdl",
    "models/smallbridge/hulls_dw/sbhulldwedh2.mdl",
    "models/smallbridge/hulls_dw/sbhulldwedh3.mdl",
    "models/smallbridge/hulls_dw/sbhulldwedh4.mdl",
    "models/smallbridge/hulls_dw/sbhulldweflip.mdl",
    "models/smallbridge/hulls_dw/sbhulldwend.mdl",
    "models/smallbridge/hulls_dw/sbhulldwend2.mdl",
    "models/smallbridge/hulls_dw/sbhulldwenddh.mdl",
    "models/smallbridge/hulls_dw/sbhulldwenddh2.mdl",
    "models/smallbridge/hulls_dw/sbhulldwr.mdl",
    "models/smallbridge/hulls_dw/sbhulldwrdh.mdl",
    "models/smallbridge/hulls_dw/sbhulldwt.mdl",
    "models/smallbridge/hulls_dw/sbhulldwtdh.mdl",
    "models/smallbridge/hulls_dw/sbhulldwtdl.mdl",
    "models/smallbridge/hulls_dw/sbhulldwtsl.mdl",
    "models/smallbridge/hulls_dw/sbhulldwx.mdl",
    "models/smallbridge/hulls_dw/sbhulldwxdh.mdl",
    "models/smallbridge/hulls_dw/sbhulldwxdl.mdl"
}

SMT.SmallBridge["Ship Parts"] = {
    "models/smallbridge/ship parts/sbcockpit1.mdl",
    "models/smallbridge/ship parts/sbcockpit2.mdl",
    "models/smallbridge/ship parts/sbcockpit2o.mdl",
    "models/smallbridge/ship parts/sbcockpit2or.mdl",
    "models/smallbridge/ship parts/sbcockpit3.mdl",
    "models/smallbridge/ship parts/sbcockpit4.mdl",
    "models/smallbridge/ship parts/sbcockpit5dw.mdl",
    "models/smallbridge/ship parts/sbcockpith2.mdl",
    "models/smallbridge/ship parts/sbcockpitw2h2.mdl",
    "models/smallbridge/ship parts/sbengine1.mdl",
    "models/smallbridge/ship parts/sbengine2.mdl",
    "models/smallbridge/ship parts/sbengine2o.mdl",
    "models/smallbridge/ship parts/sbengine2or.mdl",
    "models/smallbridge/ship parts/sbengine3.mdl",
    "models/smallbridge/ship parts/sbengine4dw.mdl",
    "models/smallbridge/ship parts/sbengine4l.mdl",
    "models/smallbridge/ship parts/sbengine4m.mdl",
    "models/smallbridge/ship parts/sbengine4r.mdl",
    "models/smallbridge/ship parts/sbengine42h.mdl",
    "models/smallbridge/ship parts/sbengine5.mdl",
    "models/smallbridge/ship parts/sbengine5dwdh.mdl",
    "models/mandrac/smallbridgeaddon/sbenginemsw.mdl",
    "models/mandrac/smallbridgeaddon/sbenginecdw.mdl",
    "models/smallbridge/ship parts/sbenginebo.mdl",
    "models/smallbridge/ship parts/sbhulldsdwe.mdl",
    "models/smallbridge/ship parts/sbhulldsdwe2.mdl",
    "models/smallbridge/ship parts/sbhulldse.mdl",
    "models/smallbridge/ship parts/sbhulldse2.mdl",
    "models/smallbridge/ship parts/sbhulldseb.mdl",
    "models/smallbridge/ship parts/sbhulldsp.mdl",
    "models/smallbridge/ship parts/sbhulldsp2.mdl",
    "models/smallbridge/ship parts/sbhulldst.mdl",
    "models/smallbridge/ship parts/sblandramp.mdl",
    "models/smallbridge/ship parts/sblandrampdw.mdl",
    "models/smallbridge/ship parts/sblandrampdwdh.mdl",
    "models/smallbridge/ship parts/sblandrampp.mdl",
    "models/smallbridge/ship parts/sblandramppdw.mdl",
    "models/smallbridge/ship parts/sblandramppdwdh.mdl",
    "models/smallbridge/ship parts/sblanduramp.mdl",
    "models/smallbridge/ship parts/sblandurampdw.mdl",
    "models/smallbridge/ship parts/sblandurampdwdh.mdl",
    "models/mandrac/smallbridgeaddon/sbcockpit3addon.mdl"
}

SMT.SmallBridge["Splitters"] = {
    "models/smallbridge/splitters/sbconvmb.mdl",
    "models/smallbridge/splitters/sbconvmbdh.mdl",
    "models/smallbridge/splitters/sbconvmbdw.mdl",
    "models/smallbridge/splitters/sbconvmbdwdh.mdl",
    "models/smallbridge/splitters/sbsplit2s-2sw.mdl",
    "models/smallbridge/splitters/sbsplit2s-dw.mdl",
    "models/smallbridge/splitters/sbsplitdws-dhd.mdl",
    "models/smallbridge/splitters/sbsplitdws-dhm.mdl",
    "models/smallbridge/splitters/sbsplitdws-dhu.mdl",
    "models/smallbridge/splitters/sbsplits-dhd.mdl",
    "models/smallbridge/splitters/sbsplits-dhm.mdl",
    "models/smallbridge/splitters/sbsplits-dhu.mdl",
    "models/smallbridge/splitters/sbsplits-dw.mdl",
    "models/smallbridge/splitters/sbsplits-dwa.mdl",
    "models/smallbridge/splitters/sbsplits-dwdh.mdl",
    "models/smallbridge/splitters/sbsplitv.mdl",
    "models/smallbridge/splitters/sbsplitvdh.mdl",
    "models/smallbridge/splitters/sbsplitvw.mdl",
    "models/smallbridge/panels/1w2wpanel.mdl",
    "models/smallbridge/panels/2w2hsplitter1.mdl",
    "models/smallbridge/panels/2w2hsplitter2.mdl"
}

SMT.SmallBridge["Height Transfer"] = {
    "models/smallbridge/height transfer/sbhtcramp.mdl",
    "models/smallbridge/height transfer/sbhtcramp2d.mdl",
    "models/smallbridge/height transfer/sbhtcramp2u.mdl",
    "models/smallbridge/height transfer/sbhtcrampdl.mdl",
    "models/smallbridge/height transfer/sbhtramp.mdl",
    "models/smallbridge/height transfer/sbhtramp05.mdl",
    "models/smallbridge/height transfer/sbhtrampdw.mdl",
    "models/smallbridge/height transfer/sbhtrampdw05.mdl",
    "models/smallbridge/height transfer/sbhtsdwrampd.mdl",
    "models/smallbridge/height transfer/sbhtsdwrampm.mdl",
    "models/smallbridge/height transfer/sbhtsdwrampu.mdl",
    "models/smallbridge/height transfer/sbhtsrampd.mdl",
    "models/smallbridge/height transfer/sbhtsrampm.mdl",
    "models/smallbridge/height transfer/sbhtsrampu.mdl",
    "models/smallbridge/height transfer/sbhtsrampz.mdl",
    "models/smallbridge/height transfer/sbhtsrampzdh.mdl",
    "models/smallbridge/height transfer/sbhtsrampzdw.mdl",
    "models/smallbridge/height transfer/sbhtsrampzdwdh.mdl",
    "models/mandrac/smallbridgeaddon/sbhtsladder.mdl"
}

SMT.SmallBridge["Panels"] = {
    "models/smallbridge/panels/sbdoor.mdl",
    "models/smallbridge/panels/sbdoorsquare.mdl",
    "models/smallbridge/panels/sbdoorwide.mdl",
    "models/smallbridge/panels/sbpaneldbsmall.mdl",
    "models/smallbridge/panels/sbpaneldh.mdl",
    "models/smallbridge/panels/sbpaneldhdw.mdl",
    "models/smallbridge/panels/sbpaneldockin.mdl",
    "models/smallbridge/panels/sbpaneldockout.mdl",
    "models/smallbridge/panels/sbpaneldoor.mdl",
    "models/smallbridge/panels/sbpaneldoordh.mdl",
    "models/smallbridge/panels/sbpaneldoordhdw.mdl",
    "models/smallbridge/panels/sbpaneldoordw.mdl",
    "models/smallbridge/panels/sbpaneldoordw2.mdl",
    "models/smallbridge/panels/sbpaneldooriris.mdl",
    "models/smallbridge/panels/sbpaneldoorsquare.mdl",
    "models/smallbridge/panels/sbpaneldoorsquaredw.mdl",
    "models/smallbridge/panels/sbpaneldoorsquaredw2.mdl",
    "models/smallbridge/panels/sbpaneldoorwide.mdl",
    "models/smallbridge/panels/sbpaneldoorwide2.mdl",
    "models/smallbridge/panels/sbpaneliris.mdl",
    "models/smallbridge/panels/sbpanelsolid.mdl",
    "models/smallbridge/panels/sbpanelsoliddw.mdl",
    "models/mandrac/smallbridgeaddon/2room.mdl"
}

SMT.SmallBridge["Elevators, Small"] = {
    "models/smallbridge/elevators_small/sbselevb.mdl",
    "models/smallbridge/elevators_small/sbselevbe.mdl",
    "models/smallbridge/elevators_small/sbselevbedh.mdl",
    "models/smallbridge/elevators_small/sbselevbedw.mdl",
    "models/smallbridge/elevators_small/sbselevbr.mdl",
    "models/smallbridge/elevators_small/sbselevbt.mdl",
    "models/smallbridge/elevators_small/sbselevbx.mdl",
    "models/smallbridge/elevators_small/sbselevm.mdl",
    "models/smallbridge/elevators_small/sbselevme.mdl",
    "models/smallbridge/elevators_small/sbselevmedh.mdl",
    "models/smallbridge/elevators_small/sbselevmedw.mdl",
    "models/smallbridge/elevators_small/sbselevmr.mdl",
    "models/smallbridge/elevators_small/sbselevmt.mdl",
    "models/smallbridge/elevators_small/sbselevmx.mdl",
    "models/smallbridge/elevators_small/sbselevp0.mdl",
    "models/smallbridge/elevators_small/sbselevp1.mdl",
    "models/smallbridge/elevators_small/sbselevp2e.mdl",
    "models/smallbridge/elevators_small/sbselevp2esl.mdl",
    "models/smallbridge/elevators_small/sbselevp2r.mdl",
    "models/smallbridge/elevators_small/sbselevp3.mdl",
    "models/smallbridge/elevators_small/sbselevs.mdl",
    "models/smallbridge/elevators_small/sbselevs2.mdl",
    "models/smallbridge/elevators_small/sbselevslant.mdl",
    "models/smallbridge/elevators_small/sbselevt.mdl",
    "models/smallbridge/elevators_small/sbselevte.mdl",
    "models/smallbridge/elevators_small/sbselevtedh.mdl",
    "models/smallbridge/elevators_small/sbselevtedw.mdl",
    "models/smallbridge/elevators_small/sbselevtr.mdl",
    "models/smallbridge/elevators_small/sbselevtt.mdl",
    "models/smallbridge/elevators_small/sbselevtx.mdl"
}

SMT.SmallBridge["Elevators, Large"] = {
    "models/smallbridge/elevators_large/sblelevb.mdl",
    "models/smallbridge/elevators_large/sblelevbe.mdl",
    "models/smallbridge/elevators_large/sblelevbedh.mdl",
    "models/smallbridge/elevators_large/sblelevbr.mdl",
    "models/smallbridge/elevators_large/sblelevbt.mdl",
    "models/smallbridge/elevators_large/sblelevbx.mdl",
    "models/smallbridge/elevators_large/sblelevm.mdl",
    "models/smallbridge/elevators_large/sblelevme.mdl",
    "models/smallbridge/elevators_large/sblelevmedh.mdl",
    "models/smallbridge/elevators_large/sblelevmr.mdl",
    "models/smallbridge/elevators_large/sblelevmt.mdl",
    "models/smallbridge/elevators_large/sblelevmx.mdl",
    "models/smallbridge/elevators_large/sblelevp0.mdl",
    "models/smallbridge/elevators_large/sblelevp1.mdl",
    "models/smallbridge/elevators_large/sblelevp2e.mdl",
    "models/smallbridge/elevators_large/sblelevp2r.mdl",
    "models/smallbridge/elevators_large/sblelevp3.mdl",
    "models/smallbridge/elevators_large/sblelevs.mdl",
    "models/smallbridge/elevators_large/sblelevs2.mdl",
    "models/smallbridge/elevators_large/sblelevt.mdl",
    "models/smallbridge/elevators_large/sblelevte.mdl",
    "models/smallbridge/elevators_large/sblelevtedh.mdl",
    "models/smallbridge/elevators_large/sblelevtr.mdl",
    "models/smallbridge/elevators_large/sblelevtt.mdl",
    "models/smallbridge/elevators_large/sblelevtx.mdl"
}

SMT.SmallBridge["Hangars"] = {
    "models/smallbridge/hangars/sbdb1l.mdl",
    "models/smallbridge/hangars/sbdb1ls.mdl",
    "models/smallbridge/hangars/sbdb1m.mdl",
    "models/smallbridge/hangars/sbdb1m1.mdl",
    "models/smallbridge/hangars/sbdb1m12.mdl",
    "models/smallbridge/hangars/sbdb1r.mdl",
    "models/smallbridge/hangars/sbdb1rs.mdl",
    "models/smallbridge/hangars/sbdb2l.mdl",
    "models/smallbridge/hangars/sbdb2m.mdl",
    "models/smallbridge/hangars/sbdb2mdw.mdl",
    "models/smallbridge/hangars/sbdb2r.mdl",
    "models/smallbridge/hangars/sbdb3m.mdl",
    "models/smallbridge/hangars/sbdb3mdw.mdl",
    "models/smallbridge/hangars/sbdb3mx.mdl",
    "models/smallbridge/hangars/sbdb3mxdw.mdl",
    "models/smallbridge/hangars/sbdb3side.mdl",
    "models/smallbridge/hangars/sbdb4l.mdl",
    "models/smallbridge/hangars/sbdb4m.mdl",
    "models/smallbridge/hangars/sbdb4mdw.mdl",
    "models/smallbridge/hangars/sbdb4r.mdl",
    "models/smallbridge/hangars/sbdbcomp1.mdl",
    "models/smallbridge/hangars/sbdbseg1s.mdl",
    "models/smallbridge/hangars/sbdbseg1ss.mdl",
    "models/smallbridge/hangars/sbdbseg2s.mdl",
    "models/smallbridge/hangars/sbdbseg3s.mdl",
    "models/smallbridge/hangars/sbdbseg4s.mdl"
}

SMT.SmallBridge["Station Parts"] = {
    "models/smallbridge/station parts/sbbayaps.mdl",
    "models/smallbridge/station parts/sbbaydps.mdl",
    "models/smallbridge/station parts/sbbridgecomm.mdl",
    "models/smallbridge/station parts/sbbridgecommdw.mdl",
    "models/smallbridge/station parts/sbbridgecommelev.mdl",
    "models/smallbridge/station parts/sbbridgesphere.mdl",
    "models/smallbridge/station parts/sbbridgevisor.mdl",
    "models/smallbridge/station parts/sbbridgevisorb.mdl",
    "models/smallbridge/station parts/sbbridgevisorm.mdl",
    "models/smallbridge/station parts/sbbridgevisort.mdl",
    "models/smallbridge/station parts/sbdockcs.mdl",
    "models/smallbridge/station parts/sbhangarld.mdl",
    "models/smallbridge/station parts/sbhangarlu.mdl",
    "models/smallbridge/station parts/sbhangarlud.mdl",
    "models/smallbridge/station parts/sbhangarlud2.mdl",
    "models/smallbridge/station parts/sbhubl.mdl",
    "models/smallbridge/station parts/sbhuble.mdl",
    "models/smallbridge/station parts/sbhubls.mdl",
    "models/smallbridge/station parts/sbhubs.mdl",
    "models/smallbridge/station parts/sbrooml1.mdl",
    "models/smallbridge/station parts/sbroomsgc.mdl",
    "models/mandrac/smallbridgeaddon/biodome.mdl"
}

SMT.SmallBridge["Walkways"] = {
    "models/smallbridge/walkways/sbwalkwaye.mdl",
    "models/smallbridge/walkways/sbwalkwaye2.mdl",
    "models/smallbridge/walkways/sbwalkwayr.mdl",
    "models/smallbridge/walkways/sbwalkwayt.mdl",
    "models/smallbridge/walkways/sbwalkwayx.mdl"
}

SMT.SmallBridge["Other"] = {
    "models/smallbridge/other/sbconsole.mdl",
    "models/smallbridge/other/sbconsolelow.mdl",
    "models/smallbridge/other/sbconsoletop.mdl"
}

SMT.SmallBridge["Wings"] = {
    "models/smallbridge/wings/sbwingc1l.mdl",
    "models/smallbridge/wings/sbwingc1r.mdl",
    "models/smallbridge/wings/sbwingls1l.mdl",
    "models/smallbridge/wings/sbwingls1r.mdl",
    "models/smallbridge/wings/sbwingm1l.mdl",
    "models/smallbridge/wings/sbwingm1le.mdl",
    "models/smallbridge/wings/sbwingm1r.mdl",
    "models/smallbridge/wings/sbwingm1re.mdl",
    "models/smallbridge/wings/sbwings1l.mdl",
    "models/smallbridge/wings/sbwings1r.mdl"
}

SMT.SmallBridge["Ships"] = {
    "models/smallbridge/ships/hysteria_galapagos.mdl",
    "models/smallbridge/ships/matthew0623_hydra.mdl",
    "models/smallbridge/ships/sbfrigate1.mdl",
    "models/smallbridge/ships/sbshuttlec1e1.mdl",
    "models/smallbridge/ships/sbshuttlec1e2.mdl",
    "models/smallbridge/ships/sbshuttlec2e2.mdl",
    "models/smallbridge/ships/steakknife.mdl",
    "models/smallbridge/ships/wilkie1020.mdl"
}

SMT.SmallBridge["Cohesion"] = {
    "models/smallbridge/experimental/hulls_sw/sbhullend.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullendf1.mdl",
    "models/smallbridge/experimental/hulls_sw/sbhulle05.mdl",
    "models/smallbridge/experimental/hulls_sw/sbhulle1.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhulle1f1.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhulle1f2.mdl",
    "models/smallbridge/experimental/hulls_sw/sbhullr.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullrf1.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullrf2.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullrf2a.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullrf3.mdl",
    "models/smallbridge/experimental/hulls_sw/sbhullt.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhulltf1.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhulltf2.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhulltf3.mdl",
    "models/smallbridge/experimental/hulls_sw/sbhullx.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullxf1.mdl",
    "models/smallbridge/cohesion/hulls_sw/sbhullxf2.mdl"
}


for k, v in pairs(SMT) do
    list.Set("SBEP_SmallBridgeModels", k, v)
end
local SMT = {}
  SMT.ModBridge = {}
    SMT.ModBridge["Hulls (MoB)"] =
  {
    "models/cerus/modbridge/core/cvw-11-31.mdl",
   
    "models/cerus/modbridge/core/c-111.mdl",
    "models/cerus/modbridge/core/c-131l.mdl",
    "models/cerus/modbridge/core/c-131r.mdl",
    "models/cerus/modbridge/core/c-221.mdl",
    "models/cerus/modbridge/core/c-331.mdl",
    "models/cerus/modbridge/core/c-332.mdl",
   
    "models/cerus/modbridge/core/cv-21-31.mdl",
    "models/cerus/modbridge/core/cv-11-21.mdl",
    "models/cerus/modbridge/core/cv-11-31.mdl",
   
    "models/cerus/modbridge/core/s-111.mdl",
    "models/cerus/modbridge/core/s-221.mdl",
    "models/cerus/modbridge/core/s-221g.mdl",
    "models/cerus/modbridge/core/s-231.mdl",
    "models/cerus/modbridge/core/s-311.mdl",
    "models/cerus/modbridge/core/s-331g.mdl",
    "models/cerus/modbridge/core/s-111g.mdl",
    "models/cerus/modbridge/core/s-121.mdl",
    "models/cerus/modbridge/core/s-131.mdl",
    "models/cerus/modbridge/core/s-211.mdl",
    "models/cerus/modbridge/core/s-321.mdl",
    "models/cerus/modbridge/core/s-331.mdl",
    "models/cerus/modbridge/core/s-332.mdl",
   
    "models/cerus/modbridge/core/sc-111.mdl",
    "models/cerus/modbridge/core/sc-131g.mdl",
    "models/cerus/modbridge/core/sc-131g3.mdl",
    "models/cerus/modbridge/core/sc-111g.mdl",
    "models/cerus/modbridge/core/sc-121.mdl",
    "models/cerus/modbridge/core/sc-131.mdl",
    "models/cerus/modbridge/core/sc-131g2.mdl",
    "models/cerus/modbridge/core/sc-332.mdl",
   
    "models/cerus/modbridge/core/t-331.mdl",
    "models/cerus/modbridge/core/t-111.mdl",
    "models/cerus/modbridge/core/t-131.mdl",
    "models/cerus/modbridge/core/t-221.mdl",
    "models/cerus/modbridge/core/t-332.mdl",
   
    "models/cerus/modbridge/core/x-331.mdl",
    "models/cerus/modbridge/core/x-111.mdl",
    "models/cerus/modbridge/core/x-221.mdl",
    "models/cerus/modbridge/core/x-332.mdl",
   
    "models/cerus/modbridge/core/bridgeg-211.mdl",
   
    "models/cerus/modbridge/core/tc-131.mdl"
  }
  SMT.ModBridge["Spartan (MoB)"] =
  {
    "models/cerus/modbridge/core/spartan/c-111.mdl",
    "models/cerus/modbridge/core/spartan/c-221.mdl",
    "models/cerus/modbridge/core/spartan/cv-11-31.mdl",
    "models/cerus/modbridge/core/spartan/s-111.mdl",
    "models/cerus/modbridge/core/spartan/s-121.mdl",
    "models/cerus/modbridge/core/spartan/s-131.mdl",
    "models/cerus/modbridge/core/spartan/s-211.mdl",
    "models/cerus/modbridge/core/spartan/s-221.mdl",
    "models/cerus/modbridge/core/spartan/s-231.mdl",
    "models/cerus/modbridge/core/spartan/s-311.mdl",
    "models/cerus/modbridge/core/spartan/s-321.mdl",
    "models/cerus/modbridge/core/spartan/s-331.mdl"
  }
    SMT.ModBridge["Ship parts (MoB)"] =
  {
    "models/cerus/modbridge/core/g-211s.mdl",
    "models/cerus/modbridge/core/g-221.mdl",
    "models/cerus/modbridge/core/g-111wd.mdl",
    "models/cerus/modbridge/core/g-221s.mdl",
    "models/cerus/modbridge/core/g-231r.mdl",
    "models/cerus/modbridge/core/g-231s.mdl",
    "models/cerus/modbridge/core/g-231w.mdl"
  }
    SMT.ModBridge["Height transfer (MoB)"] =
  {
    "models/cerus/modbridge/core/rs-322.mdl",
    "models/cerus/modbridge/core/rs-332.mdl",
    "models/cerus/modbridge/core/rs-312.mdl",
   
    "models/cerus/modbridge/core/rso-322.mdl",
    "models/cerus/modbridge/core/rso-332.mdl",
    "models/cerus/modbridge/core/rso-312.mdl",
    "models/cerus/modbridge/core/rso-332f.mdl",
   
    "models/cerus/modbridge/core/rst-312.mdl",
    "models/cerus/modbridge/core/rst-322r.mdl",
    "models/cerus/modbridge/core/rst-322l.mdl",
    "models/cerus/modbridge/core/rst-332.mdl",
    "models/cerus/modbridge/core/rst-332c.mdl",
    "models/cerus/modbridge/core/rst-332cf.mdl",
    "models/cerus/modbridge/core/rst-332f.mdl",
   
    "models/cerus/modbridge/core/r-312.mdl"
  }
    SMT.ModBridge["Elevators (MoB)"] =
  {
    "models/cerus/modbridge/core/s-331eb.mdl",
    "models/cerus/modbridge/core/s-331em.mdl",
    "models/cerus/modbridge/core/s-331et.mdl",
    "models/cerus/modbridge/core/s-332ep.mdl",
    "models/cerus/modbridge/misc/elevator/se11f.mdl",
   
    "models/cerus/modbridge/misc/elevator/eb111.mdl",
    "models/cerus/modbridge/misc/elevator/ecb111.mdl",
    "models/cerus/modbridge/misc/elevator/ecm111.mdl",
    "models/cerus/modbridge/misc/elevator/ect111.mdl",
    "models/cerus/modbridge/misc/elevator/em111.mdl",
    "models/cerus/modbridge/misc/elevator/et111.mdl",
   
    "models/cerus/modbridge/misc/elevator/elev_111.mdl",
   
    "models/cerus/modbridge/misc/elevator/eb332.mdl",
    "models/cerus/modbridge/misc/elevator/em332.mdl",
    "models/cerus/modbridge/misc/elevator/et332.mdl",
   
    "models/cerus/modbridge/misc/elevator/elev_332.mdl",
    "models/cerus/modbridge/misc/elevator/elev_332b.mdl",
   
    "models/cerus/modbridge/misc/elevator/etm111.mdl",
    "models/cerus/modbridge/misc/elevator/etm111g.mdl",
    "models/cerus/modbridge/misc/elevator/etm112.mdl",
    "models/cerus/modbridge/misc/elevator/etm113.mdl",
    "models/cerus/modbridge/misc/elevator/etm113g.mdl"
  }
  SMT.ModBridge["Other (MoB)"] =
  {
    "models/cerus/modbridge/core/prefab/crew_331.mdl",
    "models/cerus/modbridge/core/cv-mb-smb.mdl"
  }

for k,v in pairs( SMT ) do
  list.Set( "SBEP_SmallBridgeModels", k , v )
end
local SMT = {}
  SMT.MedBridge = {}
  SMT.MedBridge["MedBridge Hulls"] =
  {
  	"models/sbep_community/d12mbsframe.mdl",
	"models/slyfo/angledown.mdl",
	"models/slyfo/angleup.mdl",
	"models/slyfo/bottomless.mdl",
	"models/slyfo/doublehatch.mdl",
	"models/slyfo/doublehull.mdl",
	"models/slyfo/doublehullramp.mdl",
	"models/slyfo/doublesideopen.mdl",
	"models/slyfo/doubletrishort.mdl",
	"models/slyfo/dw_cargo.mdl",
	"models/slyfo/dw_cargoramp.mdl",
	"models/slyfo/dw_double_ramp.mdl",
	"models/slyfo/dw_sw_conv.mdl",
	"models/slyfo/dw_sw_convleft.mdl",
	"models/slyfo/dw_sw_convright.mdl",
	"models/slyfo/dwbent.mdl",
	"models/slyfo/dwbump.mdl",
	"models/slyfo/dwsmooth.mdl",
	"models/slyfo/fishfacemki.mdl",
	"models/slyfo/inversebay.mdl",
	"models/slyfo/inverter.mdl",
	"models/slyfo/inverthull.mdl",
	"models/slyfo/inverthull_ramp.mdl",
	"models/slyfo/joint_90short.mdl",
	"models/slyfo/largerad.mdl",
	"models/slyfo/largetri.mdl",
	"models/slyfo/ljoint.mdl",
	"models/slyfo/longhangar.mdl",
	"models/slyfo/longlass.mdl",
	"models/slyfo/longnoglass.mdl",
	"models/slyfo/mcpdropbay.mdl",
	"models/slyfo/mcpdropglass.mdl",
	"models/slyfo/medglass.mdl",
	"models/slyfo/mednoglass.mdl",
	"models/slyfo/minelayer.mdl",
	"models/slyfo/ramp.mdl",
	"models/slyfo/rampleft.mdl",
	"models/slyfo/rampright.mdl",
	"models/slyfo/shangar.mdl",
	"models/slyfo/shortglass.mdl",
	"models/slyfo/shortnoglass.mdl",
	"models/slyfo/sideconv.mdl",
	"models/slyfo/sideconv_ramp.mdl",
	"models/slyfo/smallrad.mdl",
	"models/slyfo/smalltri.mdl",
	"models/slyfo/smuggler_double.mdl",
	"models/slyfo/smuggler_single.mdl",
	"models/slyfo/smuggler_single2.mdl",
	"models/slyfo/smuggler_single3.mdl",
	"models/slyfo/straighthull.mdl",
	"models/slyfo/sw_cargo.mdl",
	"models/slyfo/sw_cargoramp.mdl",
	"models/slyfo/sw_dwroomlong.mdl",
	"models/slyfo/sw_dwroomshort.mdl",
	"models/slyfo/thhull.mdl",
	"models/slyfo/thlong.mdl",
	"models/slyfo/thnoramp.mdl",
	"models/slyfo/thramp.mdl",
	"models/slyfo/tjoint.mdl",
	"models/slyfo/tjointdouble.mdl",
	"models/slyfo/tramp.mdl",
	"models/slyfo/trampdouble.mdl",
	"models/slyfo/tramptriple.mdl",
	"models/slyfo/tramptripleinv.mdl",
	"models/slyfo/triangularhub.mdl",
	"models/slyfo/trit.mdl",
	"models/slyfo/turnabout.mdl",
	"models/slyfo/vert_transfer.mdl",
	"models/slyfo/xjoint.mdl",
	"models/slyfo/xjointdouble.mdl",
	"models/slyfo/xramp.mdl",
	"models/slyfo/xrampdouble.mdl",
	"models/slyfo_2/telepad_inhull.mdl",
	"models/spacebuild/nova/hull_lift1.mdl",
	"models/spacebuild/nova/hull_lift_double.mdl",
	"models/twinbladetm/enginecontrolmk2.mdl",
	"models/twinbladetm/entrymk2.mdl",

  }
  SMT.MedBridge["Medbridge2 Hulls"] =
  {
  "models/spacebuild/MedBridge2_emptyhull.mdl",
  "models/spacebuild/MedBridge2_emptyhull_90.mdl",
  "models/spacebuild/MedBridge2_emptyhull_t.mdl",
  "models/spacebuild/MedBridge2_emptyhull_x.mdl",
  "models/spacebuild/MedBridge2_compflathull.mdl",
  "models/spacebuild/medbridge2_compflatdoublehull.mdl",
  "models/spacebuild/medbridge2_compflatdoublehull_centralcolumnelevator.mdl",
  "models/spacebuild/medbridge2_compflatdoublehull_elevatorshaft.mdl",
  "models/spacebuild/medbridge2_emptydoublehull.mdl",
  "models/spacebuild/medbridge2_emptydoublehull_decktodeckramp.mdl",
  "models/spacebuild/medbridge2_singletodoublehull.mdl",
  "models/spacebuild/medbridge2_stackdoublehull.mdl",
  "models/spacebuild/medbridge2_stackdoublehull_ramp.mdl",
  "models/spacebuild/medbridge2_widey.mdl",
  }
  SMT.MedBridge["MedBridge Decks"] = 
  {
	"models/slyfo/fdeck_long_invert.mdl",
	"models/slyfo/fdeck_long.mdl",
	"models/slyfo/fdeck_long_invertbottom.mdl",
	"models/slyfo/fdeck_longtop.mdl",
	"models/slyfo/fdeck_short.mdl",
	"models/slyfo/fdeck_short_invert.mdl",
	"models/slyfo/fdeck_short_invertbottom.mdl",
	"models/slyfo/fdeck_shortramp_invert.mdl",
	"models/slyfo/fdeck_shortramp_invertbottom.mdl",
	"models/slyfo/fdeck_shortramp_invertbottomdual.mdl",
	"models/slyfo/fdeck_shorttop.mdl",
  }
  SMT.MedBridge["MedBridge Ship Parts"]=
  {
	"models/punisher239/punisher239_engine_lms.mdl",
	"models/sbep_community/d12mbbridge.mdl",
	"models/sbep_community/d12mbcubconsingle.mdl",
	"models/sbep_community/d12mbdome.mdl",
	"models/sbep_community/d12singengine.mdl",
	"models/slyfo/airlock.mdl",
	"models/slyfo/biodome.mdl",
	"models/slyfo/cockpit_lground.mdl",
	"models/slyfo/cockpit_sideround.mdl",
	"models/slyfo/cockpit_smround.mdl",
	"models/slyfo/combat_cockpit_small.mdl",
	"models/slyfo/cruisercockpit.mdl",
	"models/slyfo/gallant_class_engine1.mdl",
	"models/slyfo/gallant_class_engine2.mdl",
	"models/slyfo/gallant_class_engine3.mdl",
	"models/slyfo/gallant_class_engine4.mdl",
	"models/slyfo/gallant_class_engine5.mdl",
	"models/slyfo/gallant_class_engine6.mdl",
	"models/slyfo/gallant_cockpitdoublehuge.mdl",
	"models/slyfo/matthewengineshort.mdl",
	"models/slyfo/matthewenginelong.mdl",
	"models/slyfo/sccleft.mdl",
	"models/slyfo/sccright.mdl",
	"models/slyfo/sidecockpit.mdl",
	"models/slyfo/thcockpit.mdl",
	"models/slyfo_2/engine_sa_dp1_doublenoramp.mdl",
	"models/slyfo_2/engine_sa_dp1_doubleramp.mdl",
	"models/slyfo_2/engine_sa_dp1_huge1.mdl",
	"models/slyfo_2/engine_sa_dp1_huge2.mdl",
	"models/slyfo_2/engine_sa_dp1_huge3.mdl",
	"models/slyfo_2/engine_sa_dp1_single1.mdl",
	"models/slyfo_2/engine_sa_dp1_single2.mdl",
	"models/slyfo_2/engine_sa_dp1_single3.mdl",
	"models/slyfo_2/hull_singugen.mdl",
	"models/slyfo_2/hull_singugeninv.mdl",
	"models/slyfo_2/hull_singugenwide.mdl",
	"models/slyfo_2/hull_singugenwideinv.mdl",
	"models/spacebuild/nova/braudside1.mdl",
	"models/spacebuild/nova/crewquarters.mdl",
	"models/spacebuild/nova/plowbridge.mdl",
	"models/spacebuild/nova/supercarrierbridge.mdl",
	"models/spacebuild/nova/tallbridge.mdl",
	"models/twinbladetm/centralcontrol.mdl",
	"models/twinbladetm/enginemk2.mdl",
	"models/twinbladetm/plowbridgemk2.mdl",
  }
  SMT.MedBridge["Medbridge2 Ship Parts"] =
  {
  "models/spacebuild/medbridge.mdl",
  "models/spacebuild/medbridge2.mdl",
  "models/spacebuild/medbridge2_360view_doublebridge.mdl",
  "models/spacebuild/medbridge2_angularbridge.mdl",
  "models/spacebuild/medbridge2_engineaddon1.mdl",
  "models/spacebuild/medbridge2_enginedoublehull2_narrow.mdl",
  "models/spacebuild/medbridge2_enginedoublehull2_wide.mdl",
  "models/spacebuild/medbridge2_enginedoublehull_flaps.mdl",
  "models/spacebuild/medbridge2_enginehull.mdl",
  "models/spacebuild/medbridge2_enginehull2.mdl",
  "models/spacebuild/medbridge2_enginehull3.mdl",
  "models/spacebuild/medbridge2_enginehull4.mdl",
  "models/spacebuild/medbridge2_longbridge.mdl",
  "models/spacebuild/medbridge2_midsection_doublebridge.mdl",
  "models/spacebuild/medbridge2_midsection_doublebridge2.mdl",
  "models/spacebuild/medbridge2_midsectionbridge.mdl",
  "models/spacebuild/medbridge2_twolevel.mdl",
  }
  SMT.MedBridge["MedBridge Hangars"] = 
  {
  "models/slyfo/capturehull1.mdl",
  "models/slyfo/doubleclamp.mdl",
  "models/slyfo/doubleclamp_x.mdl",
  "models/slyfo/hangar1.mdl",
  "models/slyfo/hangar2.mdl",
  "models/slyfo/hangar3.mdl",
  "models/slyfo/hangar_singleside.mdl",
  "models/slyfo/side_pod.mdl",
  "models/twinbladetm/hangarmk2.mdl",
  }
  SMT.MedBridge["MedBridge2 Hangars"] =
  {
  "models/spacebuild/medbridge2_fighterbay.mdl",
  "models/spacebuild/medbridge2_fighterbay2.mdl",
  "models/spacebuild/medbridge2_fighterbay2_noglass.mdl",
  "models/spacebuild/medbridge2_fighterbay3.mdl",
  "models/spacebuild/medbridge2_fighterbay3a.mdl",
  "models/spacebuild/medbridge2_fighterbay3transcap.mdl",
  "models/spacebuild/medbridge2_fighterbay_noglass.mdl",
  "models/spacebuild/medbridge2_doublehull_hanger_elevator.mdl",
  }
  SMT.MedBridge["MedBridge Other"] =
  {
  "models/cerus/weapons/plas_cannon.mdl",
  "models/kriegshield/ksjuncr.mdl",
  "models/kriegshield/ksjunct.mdl",
  "models/kriegshield/ksjuncx.mdl",
  "models/kriegshield/ksstraight1.mdl",
  "models/kriegshield/ksstraight2.mdl",
  "models/kriegshield/kswall1.mdl",
  "models/kriegshield/kswallr.mdl",
  "models/kriegshield/kswallt.mdl",
  "models/mandrac/laser.mdl",
  "models/mandrac/laser2.mdl",
  "models/mandrac/laser3.mdl",
  "models/mandrac/laser4.mdl",
  "models/mandrac/laser5.mdl",
  "models/punisher239/punisher239_bridge_zeppeline_end_noramp.mdl",
  "models/punisher239/punisher239_bridge_zeppeline_end_ramp.mdl",
  "models/punisher239/punisher239_bridge_zeppeline_mid_noramp.mdl",
  "models/punisher239/punisher239_bridge_zeppeline_mid_ramp.mdl",
  "models/punisher239/punisher239_missilebay_light.mdl",
  "models/punisher239/punisher239_reactor_big.mdl",
  "models/punisher239/punisher239_reactor_small.mdl",
  "models/punisher239/punisher239_sidemount_small.mdl",
  "models/sbep_community/d12airscrubber.mdl",
  "models/sbep_community/d12console.mdl",
  "models/sbep_community/d12consolert.mdl",
  "models/sbep_community/d12consolescreen.mdl",
  "models/sbep_community/d12fusionbomb.mdl",
  "models/sbep_community/d12proxmine.mdl",
  "models/sbep_community/d12shieldemitter.mdl",
  "models/sbep_community/d12siesmiccharge.mdl",
  "models/sbep_community/ssnavalmid.mdl",
  "models/sbep_community/xwingbl.mdl",
  "models/sbep_community/xwingbody.mdl",
  "models/sbep_community/xwingbr.mdl",
  "models/sbep_community/xwingtl.mdl",
  "models/sbep_community/xwingtr.mdl",
  "models/sbep_community/ywing.mdl",
  "models/slyfo/ammorack_nuke.mdl",
  "models/slyfo/arwing_body.mdl",
  "models/slyfo/arwing_engineleft.mdl",
  "models/slyfo/arwing_engineright.mdl",
  "models/slyfo/arwing_wingleft.mdl",
  "models/slyfo/arwing_wingright.mdl",
  "models/slyfo/assault_pod.mdl",
  "models/slyfo/barricade.mdl",
  "models/slyfo/biodome2.mdl",
  "models/slyfo/cargocap.mdl",
  "models/slyfo/cargocapglass.mdl",
  "models/slyfo/cargocaplight.mdl",
  "models/slyfo/cargoclosed.mdl",
  "models/slyfo/cargohub.mdl",
  "models/slyfo/cargoopen.mdl",
  "models/slyfo/cargoship.mdl",
  "models/slyfo/cargostack.mdl",
  "models/slyfo/cargosideopen.mdl",
  "models/slyfo/carrierbay.mdl",
  "models/slyfo/carriersplit.mdl",
  "models/slyfo/ccockpit.mdl",
  "models/slyfo/cdeck_back.mdl",
  "models/slyfo/cdeck_bow.mdl",
  "models/slyfo/cdeck_double.mdl",
  "models/slyfo/cdeck_doublewide.mdl",
  "models/slyfo/cdeck_doublewideconv.mdl",
  "models/slyfo/cdeck_single.mdl",
  "models/slyfo/cdeck_tjoint.mdl",
  "models/slyfo/cengine.mdl",
  "models/slyfo/clunker.mdl",
  "models/slyfo/consolechair.mdl",
  "models/slyfo/consolescreenbig.mdl",
  "models/slyfo/consolescreenmed.mdl",
  "models/slyfo/consolescreensmall.mdl",
  "models/slyfo/crate_battery.mdl",
  "models/slyfo/crate_hollow_large.mdl",
  "models/slyfo/crate_hollow_largecap.mdl",
  "models/slyfo/crate_reactor.mdl",
  "models/slyfo/crate_resource_large.mdl",
  "models/slyfo/crate_resource_small.mdl",
  "models/slyfo/crate_watersmall.mdl",
  "models/slyfo/cratemover.mdl",
  "models/slyfo/deck.mdl",
  "models/slyfo/door1blocker.mdl",
  "models/slyfo/door1hallway.mdl",
  "models/slyfo/door1hallwayopen.mdl",
  "models/slyfo/doublecarrier.mdl",
  "models/slyfo/drillbase_basic.mdl",
  "models/slyfo/drillplatform.mdl",
  "models/slyfo/electrolysis_gen.mdl",
  "models/slyfo/evilsphere.mdl",
  "models/slyfo/finfunnel.mdl",
  "models/slyfo/forkbase.mdl",
  "models/slyfo/forklift.mdl",
  "models/slyfo/forklift_reactor.mdl",
  "models/slyfo/forkrobot.mdl",
  "models/slyfo/frigate1.mdl",
  "models/slyfo/ftl_drive.mdl",
  "models/slyfo/gcockpitseat.mdl",
  "models/slyfo/goldfish.mdl",
  "models/slyfo/interior_boxclutter.mdl",
  "models/slyfo/interior_jailcell.mdl",
  "models/slyfo/interior_jailcelldoor.mdl",
  "models/slyfo/interior_quarters1.mdl",
  "models/slyfo/interior_storageshelves.mdl",
  "models/slyfo/interiordivision1test.mdl",
  "models/slyfo/mcp.mdl",
  "models/slyfo/mcpglass.mdl",
  "models/slyfo/minelayer.mdl",
  "models/slyfo/pallet_battery.mdl",
  "models/slyfo/probe2.mdl",
  "models/slyfo/qstbigroom.mdl",
  "models/slyfo/qstbigroomallglass.mdl",
  "models/slyfo/qstbigroomglass.mdl",
  "models/slyfo/qstcorner.mdl",
  "models/slyfo/qstcornerhall1.mdl",
  "models/slyfo/qstcornerhall2.mdl",
  "models/slyfo/qstdogbone.mdl",
  "models/slyfo/qstdonut.mdl",
  "models/slyfo/qstlong.mdl",
  "models/slyfo/qstmed.mdl",
  "models/slyfo/qsts.mdl",
  "models/slyfo/qstsoftcorner.mdl",
  "models/slyfo/qstx.mdl",
  "models/slyfo/quonset.mdl",
  "models/slyfo/quonsetallglass.mdl",
  "models/slyfo/quonsetglass.mdl",
  "models/slyfo/quonsetmid.mdl",
  "models/slyfo/refinery_large.mdl",
  "models/slyfo/refinery_small.mdl",
  "models/slyfo/rex1peice.mdl",
  "models/slyfo/rexbottom.mdl",
  "models/slyfo/rextop.mdl",
  "models/slyfo/rover_na_large.mdl",
  "models/slyfo/sat_grappler.mdl",
  "models/slyfo/sat_laser.mdl",
  "models/slyfo/sat_platform.mdl",
  "models/slyfo/sat_relay.mdl",
  "models/slyfo/sat_resourcetank.mdl",
  "models/slyfo/sat_sat1.mdl",
  "models/slyfo/shuttle.mdl",
  "models/slyfo/spbarlg.mdl",
  "models/slyfo/spbarmed.mdl",
  "models/slyfo/spbarsml.mdl",
  "models/slyfo_2/acc_sci_coolerator.mdl",
  "models/slyfo_2/acc_sci_hoterator.mdl",
  "models/slyfo_2/acc_sci_spaneltanks.mdl",
  "models/slyfo_2/acc_sci_tube1.mdl",
  "models/slyfo_2/acc_sci_tube1sml.mdl",
  "models/slyfo_2/acc_sci_tube2.mdl",
  "models/slyfo_2/acc_sci_tube2sml.mdl",
  "models/slyfo_2/acc_table1.mdl",
  "models/slyfo_2/acc_table1lg.mdl",
  "models/slyfo_2/acc_table2.mdl",
  "models/slyfo_2/acc_table2lg.mdl",
  "models/slyfo_2/bunker1.mdl",
  "models/slyfo_2/bunker1door.mdl",
  "models/slyfo_2/deathmaze.mdl",
  "models/slyfo_2/drone_groundattack.mdl",
  "models/slyfo_2/drone_mac.mdl",
  "models/slyfo_2/hpanel1big.mdl",
  "models/slyfo_2/hpanel1comp.mdl",
  "models/slyfo_2/hpanel2.mdl",
  "models/slyfo_2/hpanel3.mdl",
  "models/slyfo_2/hpanel_keyboard.mdl",
  "models/slyfo_2/hpanel_keypad.mdl",
  "models/slyfo_2/hpanelrt1sml.mdl",
  "models/slyfo_2/landingpad1.mdl",
  "models/slyfo_2/miscequipmentfieldgen.mdl",
  "models/slyfo_2/miscequipmentmount.mdl",
  "models/slyfo_2/miscequipmentradiodish.mdl",
  "models/slyfo_2/miscequipmentsolar.mdl",
  "models/slyfo_2/mortarsys_swivel.mdl",
  "models/slyfo_2/power_unit.mdl",
  "models/slyfo_2/protorover.mdl",
  "models/slyfo_2/sattelite_doomray.mdl",
  "models/slyfo_2/sml_building1.mdl",
  "models/slyfo_2/sml_building1allglass.mdl",
  "models/slyfo_2/telepad_console.mdl",
  "models/slyfo_2/telepad_standalone.mdl",
  "models/slyfowalls/fencecellbroken.mdl",
  "models/slyfowalls/fencecellnocorner.mdl",
  "models/slyfowalls/fencecellnorm.mdl",
  "models/slyfowalls/fencecornerlong.mdl",
  "models/slyfowalls/fencecornershort.mdl",
  "models/slyfowalls/fencedoor1.mdl",
  "models/slyfowalls/fencedoor2.mdl",
  "models/slyfowalls/fencedoor4.mdl",
  "models/slyfowalls/fencedoor3.mdl",
  "models/slyfowalls/fencedoorsolid.mdl",
  "models/slyfowalls/fenceentrance.mdl",
  "models/slyfowalls/fencetriwall.mdl",
  "models/slyfowalls/fenceulong.mdl",
  "models/slyfowalls/fenceushort.mdl",
  "models/slyfowalls/fenceushortgunnest.mdl",
  "models/slyfowalls/fencewalllong.mdl",
  "models/slyfowalls/fencewallmed.mdl",
  "models/slyfowalls/fencewallmedbroken.mdl",
  "models/slyfowalls/fencewallshort.mdl",
  "models/slyfowalls/guardtower.mdl",
  "models/slyfowalls/guardtowerwall.mdl",
  "models/slyfowalls/scouttower.mdl",
  "models/spacebuild/medbridge2_missile_launcher.mdl",
  "models/spacebuild/stairs.mdl",
  "models/spacebuild/strange.mdl",
  "models/spacebuild/nova/blimp.mdl",
  "models/spacebuild/nova/drone2.mdl",
  "models/spacebuild/nova/dronebase.mdl",
  "models/spacebuild/nova/dronegun.mdl",
  "models/spacebuild/nova/drop_pod.mdl",
  "models/spacebuild/nova/flak1.mdl",
  "models/spacebuild/nova/hull_lift_doublelift.mdl",
  "models/spacebuild/nova/hull_lift1lift.mdl",
  "models/spacebuild/nova/laser.mdl",
  "models/spacebuild/nova/pulsecannon2.mdl",
  "models/spacebuild/nova/recieverdish.mdl",
  "models/spacebuild/nova/shipcontrolpanel.mdl",
  "models/spacebuild/nova/toe.mdl",
  "models/spacebuild/nova/toesmall.mdl",
  "models/spacebuild/nova/wallscreens1.mdl",
  "models/twinbladetm/cryotube.mdl",
  "models/twinbladetm/cryotubemkii.mdl",
  }
  SMT.MedBridge["Medbridge2 Other"] =
  {
  "models/spacebuild/cannon1_gen.mdl",
  "models/spacebuild/doorway_invert.mdl",
  "models/spacebuild/dronefighter_1.mdl",
  "models/spacebuild/emount1_milcock4.mdl",
  "models/spacebuild/emount2_milcock4.mdl",
  "models/spacebuild/emount3_milcock6.mdl",
  "models/spacebuild/emount4_fighter.mdl",
  "models/spacebuild/medbridge2_doublehull_hanger_crosswalk.mdl",
  "models/spacebuild/medbridge2_doublehull_hanger_guardrail.mdl",
  "models/spacebuild/medbridge2_gatling_cannon.mdl",
  "models/spacebuild/medbridge2_large_solar_sail.mdl",
  "models/spacebuild/medbridge2_topplate.mdl",
  "models/spacebuild/medbridge2_topplatebendcap.mdl",
  }
for k,v in pairs( SMT ) do
  list.Set( "SBEP_SmallBridgeModels", k , v )
end
