ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Cup Noodles"
ENT.Author = "Asphid_Jackal, SLYFo"
ENT.Contact = "nullonentry"
ENT.Purpose = "Get some health."
ENT.Instructions = "Eat up!" 
ENT.Category = "SBEP - Other"
ENT.Spawnable = true
ENT.AdminOnly = false