-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--/																	DOORS																      --/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
local SMT = {}
	SMT.SmallBridge = {}
	SMT.SmallBridge["Hulls (SW)"] = {
		"models/SmallBridge/Hulls,SW/sbhullcurvel.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullcurvem.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullcurves.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulle05.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulle1.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulle2.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulle3.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulle4.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulledh.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulledh05.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulledh2.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulledh3.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulledh4.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulleflip.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullend.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullenddh.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullr.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullrdh.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullrtri.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullslanthalfl.mdl"	,
		"models/SmallBridge/Hulls,SW/sbhullslanthalfr.mdl"	,
		"models/SmallBridge/Hulls,SW/sbhullslantl.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullslantr.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullt.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulltdh.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulltdl.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulltdldw.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulltri1.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulltri2.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhulltri3.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullx.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullxdh.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullxdl.mdl"		,
		"models/SmallBridge/Hulls,SW/sbhullxdldw.mdl"			
							}

	SMT.SmallBridge["Hulls (DW)"] = {
		"models/SmallBridge/Hulls,DW/sbhulldwe05.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwe1.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwe2.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwe3.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwe4.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwedh.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwedh05.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwedh2.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwedh3.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwedh4.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldweflip.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwend.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwend2.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwenddh.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwenddh2.mdl"	,
		"models/SmallBridge/Hulls,DW/sbhulldwr.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwrdh.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwt.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwtdh.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwtdl.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwtsl.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwx.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwxdh.mdl"		,
		"models/SmallBridge/Hulls,DW/sbhulldwxdl.mdl"
							}

	SMT.SmallBridge["Ship Parts"] = {
		"models/SmallBridge/Ship Parts/sbcockpit1.mdl"		,
		"models/SmallBridge/Ship Parts/sbcockpit2.mdl"		,
		"models/SmallBridge/Ship Parts/sbcockpit2o.mdl"		,
		"models/SmallBridge/Ship Parts/sbcockpit2or.mdl"	,
		"models/SmallBridge/Ship Parts/sbcockpit3.mdl"		,
		"models/SmallBridge/Ship Parts/sbcockpit4.mdl"		,
		"models/SmallBridge/Ship Parts/sbcockpit5dw.mdl"	,
		"models/SmallBridge/Ship Parts/sbcockpith2.mdl"		,
		"models/SmallBridge/Ship Parts/sbcockpitw2h2.mdl"	,
		"models/SmallBridge/Ship Parts/sbengine1.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine2.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine2o.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine2or.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine3.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine4dw.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine4l.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine4m.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine4r.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine42h.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine5.mdl"		,
		"models/SmallBridge/Ship Parts/sbengine5dwdh.mdl"	,
		"models/mandrac/smallbridgeaddon/sbenginemsw.mdl"	,
		"models/mandrac/smallbridgeaddon/sbenginecdw.mdl"	,
		"models/SmallBridge/Ship Parts/sbenginebo.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldsdwe.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldsdwe2.mdl"	,
		"models/SmallBridge/Ship Parts/sbhulldse.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldse2.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldseb.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldsp.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldsp2.mdl"		,
		"models/SmallBridge/Ship Parts/sbhulldst.mdl"		,
		"models/SmallBridge/Ship Parts/sblandramp.mdl"		,
		"models/SmallBridge/Ship Parts/sblandrampdw.mdl"	,
		"models/SmallBridge/Ship Parts/sblandrampdwdh.mdl"	,
		"models/SmallBridge/Ship Parts/sblandrampp.mdl"		,
		"models/SmallBridge/Ship Parts/sblandramppdw.mdl"	,
		"models/SmallBridge/Ship Parts/sblandramppdwdh.mdl"	,
		"models/SmallBridge/Ship Parts/sblanduramp.mdl"		,
		"models/SmallBridge/Ship Parts/sblandurampdw.mdl"	,
		"models/SmallBridge/Ship Parts/sblandurampdwdh.mdl"	,
		"models/mandrac/smallbridgeaddon/sbcockpit3addon.mdl"	
							}

	SMT.SmallBridge["Splitters"] = {
		"models/SmallBridge/Splitters/sbconvmb.mdl"		,
		"models/SmallBridge/Splitters/sbconvmbdh.mdl"		,
		"models/SmallBridge/Splitters/sbconvmbdw.mdl"		,
		"models/SmallBridge/Splitters/sbconvmbdwdh.mdl"		,
		"models/SmallBridge/Splitters/sbsplit2s-2sw.mdl"	,
		"models/SmallBridge/Splitters/sbsplit2s-dw.mdl"		,
		"models/SmallBridge/Splitters/sbsplitdws-dhd.mdl"	,
		"models/SmallBridge/Splitters/sbsplitdws-dhm.mdl"	,
		"models/SmallBridge/Splitters/sbsplitdws-dhu.mdl"	,
		"models/SmallBridge/Splitters/sbsplits-dhd.mdl"		,
		"models/SmallBridge/Splitters/sbsplits-dhm.mdl"		,
		"models/SmallBridge/Splitters/sbsplits-dhu.mdl"		,
		"models/SmallBridge/Splitters/sbsplits-dw.mdl"		,
		"models/SmallBridge/Splitters/sbsplits-dwa.mdl"		,
		"models/SmallBridge/Splitters/sbsplits-dwdh.mdl"	,
		"models/SmallBridge/Splitters/sbsplitv.mdl"		,
		"models/SmallBridge/Splitters/sbsplitvdh.mdl"		,
		"models/SmallBridge/Splitters/sbsplitvw.mdl"		,
		"models/SmallBridge/Panels/1w2wpanel.mdl"		,
		"models/SmallBridge/Panels/2w2hsplitter1.mdl"		,
		"models/SmallBridge/Panels/2w2hsplitter2.mdl"
							}

	SMT.SmallBridge["Height Transfer"] = {
		"models/SmallBridge/Height Transfer/sbhtcramp.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtcramp2d.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtcramp2u.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtcrampdl.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtramp.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtramp05.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtrampdw.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtrampdw05.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsdwrampd.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsdwrampm.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsdwrampu.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampd.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampm.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampu.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampz.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampzdh.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampzdw.mdl"	,
		"models/SmallBridge/Height Transfer/sbhtsrampzdwdh.mdl"	,
		"models/mandrac/smallbridgeaddon/sbhtsladder.mdl"
								}

	SMT.SmallBridge["Panels"] = {
		"models/SmallBridge/Panels/sbdoor.mdl"			,
		"models/SmallBridge/Panels/sbdoorsquare.mdl"		,
		"models/SmallBridge/Panels/sbdoorwide.mdl"		,
		"models/SmallBridge/Panels/sbpaneldbsmall.mdl"		,
		"models/SmallBridge/Panels/sbpaneldh.mdl"		,
		"models/SmallBridge/Panels/sbpaneldhdw.mdl"		,
		"models/SmallBridge/Panels/sbpaneldockin.mdl"		,
		"models/SmallBridge/Panels/sbpaneldockout.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoor.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoordh.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoordhdw.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoordw.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoordw2.mdl"		,
		"models/SmallBridge/Panels/sbpaneldooriris.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoorsquare.mdl"	,
		"models/SmallBridge/Panels/sbpaneldoorsquaredw.mdl"	,
		"models/SmallBridge/Panels/sbpaneldoorsquaredw2.mdl"	,
		"models/SmallBridge/Panels/sbpaneldoorwide.mdl"		,
		"models/SmallBridge/Panels/sbpaneldoorwide2.mdl"	,
		"models/SmallBridge/Panels/sbpaneliris.mdl"		,
		"models/SmallBridge/Panels/sbpanelsolid.mdl"		,
		"models/SmallBridge/Panels/sbpanelsoliddw.mdl"		,	
		"models/mandrac/smallbridgeaddon/2room.mdl"			
						}

	SMT.SmallBridge["Elevators, Small"] = {
		"models/SmallBridge/Elevators,Small/sbselevb.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevbe.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevbedh.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevbedw.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevbr.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevbt.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevbx.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevm.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevme.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevmedh.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevmedw.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevmr.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevmt.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevmx.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevp0.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevp1.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevp2e.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevp2esl.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevp2r.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevp3.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevs.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevs2.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevslant.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevt.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevte.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevtedh.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevtedw.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevtr.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevtt.mdl"	,
		"models/SmallBridge/Elevators,Small/sbselevtx.mdl"	
								}

	SMT.SmallBridge["Elevators, Large"] = {
		"models/SmallBridge/Elevators,Large/sblelevb.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevbe.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevbedh.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevbr.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevbt.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevbx.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevm.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevme.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevmedh.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevmr.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevmt.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevmx.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevp0.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevp1.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevp2e.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevp2r.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevp3.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevs.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevs2.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevt.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevte.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevtedh.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevtr.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevtt.mdl"	,
		"models/SmallBridge/Elevators,Large/sblelevtx.mdl"	
									}

	SMT.SmallBridge["Hangars"] = {
		"models/SmallBridge/Hangars/sbdb1l.mdl"			,
		"models/SmallBridge/Hangars/sbdb1ls.mdl"		,
		"models/SmallBridge/Hangars/sbdb1m.mdl"			,
		"models/SmallBridge/Hangars/sbdb1m1.mdl"		,
		"models/SmallBridge/Hangars/sbdb1m12.mdl"		,
		"models/SmallBridge/Hangars/sbdb1r.mdl"			,
		"models/SmallBridge/Hangars/sbdb1rs.mdl"		,
		"models/SmallBridge/Hangars/sbdb2l.mdl"			,
		"models/SmallBridge/Hangars/sbdb2m.mdl"			,
		"models/SmallBridge/Hangars/sbdb2mdw.mdl"		,
		"models/SmallBridge/Hangars/sbdb2r.mdl"			,
		"models/SmallBridge/Hangars/sbdb3m.mdl"			,
		"models/SmallBridge/Hangars/sbdb3mdw.mdl"		,
		"models/SmallBridge/Hangars/sbdb3mx.mdl"		,
		"models/SmallBridge/Hangars/sbdb3mxdw.mdl"		,
		"models/SmallBridge/Hangars/sbdb3side.mdl"		,
		"models/SmallBridge/Hangars/sbdb4l.mdl"			,
		"models/SmallBridge/Hangars/sbdb4m.mdl"			,
		"models/SmallBridge/Hangars/sbdb4mdw.mdl"		,
		"models/SmallBridge/Hangars/sbdb4r.mdl"			,
		"models/SmallBridge/Hangars/sbdbcomp1.mdl"		,
		"models/SmallBridge/Hangars/sbdbseg1s.mdl"		,
		"models/SmallBridge/Hangars/sbdbseg1ss.mdl"		,
		"models/SmallBridge/Hangars/sbdbseg2s.mdl"		,
		"models/SmallBridge/Hangars/sbdbseg3s.mdl"		,
		"models/SmallBridge/Hangars/sbdbseg4s.mdl"			
							}

	SMT.SmallBridge["Station Parts"] = {
		"models/SmallBridge/Station Parts/sbbayaps.mdl"		,
		"models/SmallBridge/Station Parts/sbbaydps.mdl"		,
		"models/SmallBridge/Station Parts/sbbridgecomm.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgecommdw.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgecommelev.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgesphere.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgevisor.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgevisorb.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgevisorm.mdl"	,
		"models/SmallBridge/Station Parts/sbbridgevisort.mdl"	,
		"models/SmallBridge/Station Parts/sbdockcs.mdl"		,
		"models/SmallBridge/Station Parts/sbhangarld.mdl"	,
		"models/SmallBridge/Station Parts/sbhangarlu.mdl"	,
		"models/SmallBridge/Station Parts/sbhangarlud.mdl"	,
		"models/SmallBridge/Station Parts/sbhangarlud2.mdl"	,
		"models/SmallBridge/Station Parts/sbhubl.mdl"		,
		"models/SmallBridge/Station Parts/sbhuble.mdl"		,
		"models/SmallBridge/Station Parts/sbhubls.mdl"		,
		"models/SmallBridge/Station Parts/sbhubs.mdl"		,
		"models/SmallBridge/Station Parts/sbrooml1.mdl"		,
		"models/SmallBridge/Station Parts/sbroomsgc.mdl"	,
		"models/mandrac/smallbridgeaddon/biodome.mdl"
								}

	SMT.SmallBridge["Walkways"] = {
		"models/SmallBridge/Walkways/sbwalkwaye.mdl"		,
		"models/SmallBridge/Walkways/sbwalkwaye2.mdl"		,
		"models/SmallBridge/Walkways/sbwalkwayr.mdl"		,
		"models/SmallBridge/Walkways/sbwalkwayt.mdl"		,
		"models/SmallBridge/Walkways/sbwalkwayx.mdl"		
						}

	SMT.SmallBridge["Other"] = {
		"models/SmallBridge/Other/sbconsole.mdl"		,
		"models/SmallBridge/Other/sbconsolelow.mdl"		,
		"models/SmallBridge/Other/sbconsoletop.mdl"			
						}

	SMT.SmallBridge["Wings"] = {
		"models/SmallBridge/Wings/sbwingc1l.mdl"		,
		"models/SmallBridge/Wings/sbwingc1r.mdl"		,
		"models/SmallBridge/Wings/sbwingls1l.mdl"		,
		"models/SmallBridge/Wings/sbwingls1r.mdl"		,
		"models/SmallBridge/Wings/sbwingm1l.mdl"		,
		"models/SmallBridge/Wings/sbwingm1le.mdl"		,
		"models/SmallBridge/Wings/sbwingm1r.mdl"		,
		"models/SmallBridge/Wings/sbwingm1re.mdl"		,
		"models/SmallBridge/Wings/sbwings1l.mdl"		,
		"models/SmallBridge/Wings/sbwings1r.mdl"			
						}

	SMT.SmallBridge["Ships"] = {
		"models/SmallBridge/Ships/hysteria_galapagos.mdl"	,
		"models/SmallBridge/Ships/matthew0623_hydra.mdl"	,
		"models/SmallBridge/Ships/sbfrigate1.mdl"		,
		"models/SmallBridge/Ships/sbshuttlec1e1.mdl"		,
		"models/SmallBridge/Ships/sbshuttlec1e2.mdl"		,
		"models/SmallBridge/Ships/sbshuttlec2e2.mdl"		,
		"models/SmallBridge/Ships/steakknife.mdl"		,
		"models/SmallBridge/Ships/wilkie1020.mdl"				
						}

	SMT.SmallBridge["Cohesion"] = {
		"models/SmallBridge/Experimental/Hulls,SW/sbhullend.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullendf1.mdl"	,
		"models/SmallBridge/Experimental/Hulls,SW/sbhulle05.mdl"	,
		"models/SmallBridge/Experimental/Hulls,SW/sbhulle1.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhulle1f1.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhulle1f2.mdl"	,
		"models/SmallBridge/Experimental/Hulls,SW/sbhullr.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullrf1.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullrf2.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullrf2a.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullrf3.mdl"	,
		"models/SmallBridge/Experimental/Hulls,SW/sbhullt.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhulltf1.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhulltf2.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhulltf3.mdl"	,
		"models/SmallBridge/Experimental/Hulls,SW/sbhullx.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullxf1.mdl"	,
		"models/SmallBridge/Cohesion/Hulls,SW/sbhullxf2.mdl"	
						}


for k,v in pairs( SMT ) do
	list.Set( "SBEP_SmallBridgeModels", k , v )
end