ENT.Type 			= "anim"
ENT.Base 			= "base_gmodentity"
ENT.PrintName			= "Advanced Gyro Pod"
ENT.Author			= "Paradukes and Data"
ENT.Spawnable			= false
ENT.AdminSpawnable		= false
ENT.Owner			= nil
ENT.SPL				= nil
ENT.Firing			= false
ENT.Vec				= nil
ENT.Pitch			= 0
ENT.Yaw				= 0
ENT.Roll			= 0
ENT.MChange			= false
ENT.Speed			= 0
ENT.Active			= false
ENT.Launchy			= false
ENT.Launch			= 0
ENT.Land			= true
ENT.LandTime			= 0
ENT.TakeOff			= false
ENT.OldAngle			= Angle( 0, 0, 0 )
ENT.EPrs			= false
ENT.LTog			= false
ENT.MTog			= false
ENT.MCC				= false
ENT.GPod			= true